ALTER TABLE public.budget_periods
ADD COLUMN IF NOT EXISTS is_settled BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS settled_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS settlement_goal_id UUID REFERENCES public.financial_goals(id) ON DELETE SET NULL;
